#' Calculate the frequency of polyfunctional cells
#'
#' Calculate the frequency of cells positive for each marker combination within a defined
#' population and subtract the corresponding background. Negative values are set to zero.
#'
#' @param x A dataframe generated by the \code{\link{assignMarkerCombinations}} function,
#'   containing marker combination data along with associated metadata.
#'
#' @param md_cols A character vector specifying the names of metadata columns in \code{x}.
#'   These columns provide contextual information (e.g., participant ID, sample ID,
#'   time point).
#'
#' @param pop_col A string giving the name of the column in \code{x} that contains the
#'   population of interest. The function calculates the percentage of positive cells for
#'   each marker combination within this population. Can be obtained from any source, e.g.,
#'   annotated metacluster IDs from FlowSOM clustering or cell labels from manual gating
#'   (see \code{\link[FlowSOM]{GetFlowJoLabels}}).
#'
#' @param resolution A string specifying the column in \code{x} that defines
#'   polyfunctionality, e.g., \code{"MarkerComb"}, \code{"MarkerCount"}, or
#'   \code{"Functionality"}. Default is \code{"MarkerComb"}. Can also refer to any of the
#'    logical columns generated if \code{mode = "exhaustive"} was used in
#'   \code{\link{assignMarkerCombinations}}, or to custom resolutions created by combining
#'   outputs from \code{\link{assignMarkerCombinations}}. For example,
#'   \code{atleast_IFN+TNFa+ == TRUE & MarkerCount == 3} refers to cells with three
#'   functions positive for at least IFN and TNFa. Users must first create the logical
#'   column in \code{x} (e.g., using \code{dplyr::mutate()}) before specifying it here.
#'
#' @param condition_col A string giving the name of the column in \code{x} containing the
#'   stimulation condition (e.g., antigen-stimulated, unstimulated). Default =
#'   \code{"Stimulation"}.
#'
#' @param background_val A value from \code{condition_col} indicating the background
#'   condition (e.g., "unstimulated"). This is used as the reference for stimulation
#'   conditions. Default = \code{"unstimulated"}.
#'
#' @returns A dataframe similar to \code{x}, with the addition of four new columns:
#'   \itemize{
#'     \item{\code{n_cells_pos}: Number of positive cells}
#'     \item{\code{n_cells_tot}: Number of total cells}
#'     \item{\code{perc_pos}: Percentage positive cells, i.e.
#'       \code{(n_cells_pos/n_cells_tot)*100}}
#'     \item{\code{perc_pos_backgroundSubtracted}: Percentage positive cells with
#'       corresponding background subtracted. Negative values are set to zero.}
#'   }
#' @seealso \code{\link{getMarkerPositivity}}, \code{\link{assignMarkerCombinations}}
#' @importFrom rlang .data
#' @examples
#' # Define path to data
#' path_data <- system.file("extdata", package = "polyICSFlow")
#'
#' # Read fcs files as flowSet
#' fs <- flowCore::read.flowSet(path = path_data,
#'                              pattern = ".fcs",
#'                              truncate_max_range = FALSE,
#'                              transformation = FALSE)
#'
#' # Create GatingSet
#' gs <- flowWorkspace::GatingSet(fs)
#'
#' # Apply GatingTemplate
#' gt <- openCyto::gatingTemplate(file.path(path_data,
#'                                         "gatingTemp_cytokines.csv"))
#' openCyto::gt_gating(x = gt, y = gs)
#'
#' # Get marker positivity per cell
#' df_markerPos <- getMarkerPositivity(x = gs,
#'                                     gate_names = c("IFN+","TNFa+","IL2+","CD107a+"))
#'
#' # Assign marker combinations to each cell based on marker positivity
#' df_markerComb <- assignMarkerCombinations(data_markerPos = df_markerPos,
#'                                           mode = "exhaustive")
#'
#' # Read metadata and cell labels
#' df_md <- read.csv(file.path(path_data, "metadata.csv"))
#' metacluster_labels <- readRDS(file.path(path_data, "cell_labels.rds"))
#'
#' # Add metadata and cell labels to dataframe
#' df <- df_markerComb %>%
#'     dplyr::mutate(ID = df_md$ID,
#'                   Stimulation = df_md$Stimulation,
#'                   cell_type = metacluster_labels)
#'
#' # Calculate by Marker Combination
#' result <- calcPolyfunctionality(x = df,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "MarkerComb",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#' # Calculate by Marker Count
#' result <- calcPolyfunctionality(x = df,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "MarkerCount",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#' # Calculate by Functionality
#' result <- calcPolyfunctionality(x = df,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "Functionality",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#' # Calculate by logical at least n
#' result <- calcPolyfunctionality(x = df,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "atleast_2_IFN+TNFa+",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#' # Calculate by logical Polyfunctional, at least marker
#' result <- calcPolyfunctionality(x = df,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "Polyfunctional_atleast_IFN+",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#' # Calculate by custom resolution
#' df2 <- df %>%
#'   dplyr::mutate(MarkerCountAbove3_atleast_IFN_TNFa = MarkerCount == 3 &
#'                  .data[["atleast_2_IFN+TNFa+"]])
#'
#' result <- calcPolyfunctionality(x = df2,
#'                                 md_cols = c("ID"),
#'                                 pop_col = "cell_type",
#'                                 resolution = "MarkerCountAbove3_atleast_IFN_TNFa",
#'                                 condition_col = "Stimulation",
#'                                 background_val = "Unstim")
#'
#'
#' @export
calcPolyfunctionality <- function(x, md_cols, pop_col = "cell_type", resolution = "MarkerComb", condition_col = "Stimulation", background_val = "unstimulated"){

  if(is.factor(x[[resolution]])){
    unique_polyfunct <- levels(x[[resolution]])
    refactor_resolution <- TRUE
  }else{
    unique_polyfunct <- unique(x[[resolution]])
    refactor_resolution <- FALSE
  }
  group_cols <- c(md_cols, pop_col, condition_col)

  # Calculate frequency
  df_freq <- x %>%
    dplyr::select(!!!rlang::syms(c(group_cols, resolution)))%>%
    dplyr::count(!!!rlang::syms(c(group_cols, resolution))) %>% # Count dynamically using group columns
    tidyr::complete(!!!rlang::syms(group_cols),
                    !!rlang::sym(resolution) := unique_polyfunct,
                    fill = list(n = 0)) %>% # Ensure all polyfunctionality levels exist (when count = 0)
    dplyr::rename(n_cells_pos = "n")%>%
    dplyr::group_by(!!!rlang::syms(group_cols)) %>%
    dplyr::mutate(n_cells_tot = sum(.data$n_cells_pos), # Sum of all cells in the group
                  perc_pos = 100 * .data$n_cells_pos / .data$n_cells_tot) %>% # Compute percentage
    dplyr::filter(.data$n_cells_tot > 0)%>% # Remove rows with no cells
    dplyr::ungroup()

  # Subtrack background
  df_freq <- df_freq %>%
    dplyr::group_by(dplyr::across(-c(tidyselect::all_of(condition_col), "n_cells_pos", "n_cells_tot", "perc_pos"))) %>%
    dplyr::mutate(background_perc = dplyr::if_else(any(!!rlang::sym(condition_col) == background_val),
                                                   .data$perc_pos[!!rlang::sym(condition_col) == background_val][1],
                                                   NA_real_),
                  perc_pos_backgroundSubtracted = dplyr::if_else(is.na(.data$background_perc),
                                                                 NA_real_,
                                                                 pmax(.data$perc_pos - .data$background_perc, 0)))%>%
    dplyr::select(-"background_perc")%>%
    dplyr::ungroup()

  # Check all backgrounds are zero after background subtraction
  stopifnot(all(df_freq %>% dplyr::filter(!!rlang::sym(condition_col)==background_val)%>%dplyr::pull(.data$perc_pos_backgroundSubtracted)==0))

  # Check groupings for missing background (NA values in background subtracted frequency)
  if(any(is.na(df_freq$perc_pos_backgroundSubtracted))){

    # check missing background per sample and population
    df_missing_background <- df_freq %>%
      dplyr::filter(is.na(.data$perc_pos_backgroundSubtracted))%>%
      dplyr::select(tidyselect::all_of(c(md_cols,pop_col)))%>%
      unique()

    strings <- .getStringMessages(df_missing_background, md_cols = md_cols, pop_col = pop_col)

    msg <- paste0("Background stimulation condition is missing for the following ",ifelse(nrow(df_missing_background)==1,"grouping","groupings")," (background was not subtracted):")
    message(msg)

    for(string in strings){
      message(string)
    }

  }

  # Filter out cells expressing no markers
  df_final <- df_freq %>%
    dplyr::filter(!(!!rlang::sym(resolution) %in% c(unique_polyfunct[1],"0")))

  # refactorize the resolution (if originally a factor)
  if(refactor_resolution){
    df_final[[resolution]] <- factor(df_final[[resolution]],levels = unique_polyfunct)
  }

  # Check for low cell counts (n_cells_tot<100)
  if(any(df_final$n_cells_tot<100)){

    df_small_populations <- df_final %>%
      dplyr::filter(.data$n_cells_tot<100)%>%
      dplyr::select(tidyselect::all_of(c(md_cols,pop_col)))%>%
      unique()

    strings <- .getStringMessages(df_small_populations, md_cols = md_cols, pop_col = pop_col)

    msg <- paste0("Low total cell counts (n_cells_tot < 100) have been detected in the following ", ifelse(nrow(df_small_populations)==1,"grouping","groupings"),". Please interpret these values with caution and/or consider using larger cell populations.")
    message(msg)
    for(string in strings){
      message(string)
    }
  }

  return(df_final)

}
